# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:

  yamlBasedBuilder:
    import: "package:i420n/i420n_builder.dart"
    builder_factories: ["yamlBasedBuilder"]
    build_extensions: {".i420n.yaml": [".i420n.dart"]}
    build_to: source
    auto_apply: root_package

# Global nomap flag example
# targets:
#   $default:
#     builders:
#       i420n|yamlBasedBuilder:
#         options:
#           nomap: true